# Generated by Django 3.1.1 on 2020-09-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharu', '0003_auto_20200908_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='filename',
            field=models.ImageField(default='', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
