# Generated by Django 3.1.1 on 2020-10-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaharu', '0005_auto_20201005_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='epoch',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='filename',
            field=models.FileField(upload_to='models/'),
        ),
    ]
