# Generated by Django 3.1.1 on 2020-10-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaharu', '0007_auto_20201006_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='title',
        ),
    ]
